services:
  web:
    build: .
    command: npm run start:dev
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: my_mongo_container
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_USERNAME: tsmurer
      MONGO_INITDB_PASSWORD: 1234
      MONGO_INITDB_DATABASE: urlshortenerdb

volumes:
  mongo-data: